#!/bin/bash
# Test cleanup script
# Generated on 2025-08-01T05:41:25.198Z

echo "🧹 Cleaning up unused test files..."

# Delete unused test files
rm -f "tests/e2e/admin-module-comprehensive.spec.ts"
rm -f "tests/e2e/analytics-dashboard-comprehensive.spec.ts"
rm -f "tests/e2e/auth-debug-detailed.spec.ts"
rm -f "tests/e2e/auth-test-quick.spec.ts"
rm -f "tests/e2e/business-workflows.spec.ts"
rm -f "tests/e2e/complete-workflows.spec.ts"
rm -f "tests/e2e/comprehensive-ui-tests.spec.ts"
rm -f "tests/e2e/demo-data-integrity.spec.ts"
rm -f "tests/e2e/demo-functionality.spec.ts"
rm -f "tests/e2e/finance-modules-comprehensive.spec.ts"
rm -f "tests/e2e/import-export.spec.ts"
rm -f "tests/e2e/inventory.spec.ts"
rm -f "tests/e2e/operations-modules-comprehensive.spec.ts"
rm -f "tests/e2e/test-auth-check.spec.ts"
rm -f "tests/e2e/transactions.spec.ts"
rm -f "tests/e2e/user-workflows-demo.spec.ts"
rm -f "tests/e2e/warehouse-configuration-comprehensive.spec.ts"
rm -f "tests/unit/components/charts/recharts-components.test.tsx"
rm -f "tests/unit/components/error-boundary.test.tsx"
rm -f "tests/unit/components/operations/restock-alert-card.test.tsx"
rm -f "tests/unit/components/ui/card.test.tsx"
rm -f "tests/unit/components/ui/confirm-dialog.test.tsx"
rm -f "tests/unit/components/ui/empty-state.test.tsx"
rm -f "tests/unit/components/ui/import-button.test.tsx"
rm -f "tests/unit/components/ui/page-header.test.tsx"
rm -f "tests/unit/components/ui/progress.test.tsx"
rm -f "tests/unit/components/ui/use-toast.test.tsx"
rm -f "tests/unit/hooks/index.test.ts"
rm -f "tests/unit/hooks/integration.test.tsx"
rm -f "tests/unit/hooks/useClientLogger.test.ts"
rm -f "tests/integration/api/auth.test.ts"
rm -f "tests/integration/api/dashboard-reports.test.ts"
rm -f "tests/integration/api/finance.test.ts"
rm -f "tests/integration/api/import-export.test.ts"
rm -f "tests/integration/api/inventory.test.ts"
rm -f "tests/integration/api/reconciliation-misc.test.ts"
rm -f "tests/integration/api/skus.test.ts"
rm -f "tests/integration/api/test-setup.test.ts"
rm -f "tests/integration/api/transactions.test.ts"
rm -f "tests/integration/api/user-management.test.ts"
rm -f "tests/integration/external/amazon-sp-api.test.ts"
rm -f "tests/integration/external/email-service.test.ts"
rm -f "tests/integration/inventory-flow.test.ts"
rm -f "tests/performance/baseline-metrics.test.ts"
rm -f "tests/performance/optimization-comparison.test.ts"
rm -f "tests/performance/page-load.spec.ts"
rm -f "tests/security/access-control.test.ts"
rm -f "tests/security/auth-vulnerability.test.ts"
rm -f "tests/security/csrf-protection.test.ts"
rm -f "tests/security/permission-based-access.test.ts"
rm -f "tests/security/rate-limiting.test.ts"
rm -f "tests/vulnerability-tests/api-integration/external-api-failures.test.ts"
rm -f "tests/vulnerability-tests/auth-security/auth-vulnerabilities.test.ts"
rm -f "tests/vulnerability-tests/auth-security/session-vulnerabilities.test.ts"
rm -f "tests/vulnerability-tests/data-validation/file-upload-security.test.ts"
rm -f "tests/vulnerability-tests/data-validation/input-validation.test.ts"
rm -f "tests/vulnerability-tests/e2e-edge-cases/critical-flows.spec.ts"
rm -f "tests/vulnerability-tests/e2e-edge-cases/race-condition-ui.spec.ts"
rm -f "tests/vulnerability-tests/financial-calculations/billing-edge-cases.test.ts"
rm -f "tests/vulnerability-tests/financial-calculations/financial-vulnerabilities.test.ts"
rm -f "tests/vulnerability-tests/memory-performance/performance-edge-cases.test.ts"
rm -f "tests/vulnerability-tests/race-conditions/inventory-race-conditions.test.ts"
rm -f "tests/vulnerability-tests/race-conditions/invoice-race-conditions.test.ts"
rm -f "tests/edge-cases/concurrent-actions.test.ts"
rm -f "tests/edge-cases/cross-browser-e2e.spec.ts"
rm -f "tests/edge-cases/data-integrity-failures.test.ts"
rm -f "tests/edge-cases/database-errors.test.ts"
rm -f "tests/edge-cases/file-system-errors.test.ts"
rm -f "tests/edge-cases/invalid-data-handling.test.ts"
rm -f "tests/edge-cases/memory-performance.test.ts"
rm -f "tests/edge-cases/network-failures.test.ts"
rm -f "tests/edge-cases/session-expiration.test.ts"
rm -f "tests/data-integrity/concurrent-requests.test.ts"
rm -f "tests/data-integrity/idempotency.test.ts"
rm -f "tests/data-integrity/reconciliation-accuracy.test.ts"
rm -f "tests/data-integrity/transaction-validation.test.ts"

# Clean up empty directories
find tests -type d -empty -delete

echo "✅ Cleanup complete!"
