name: Test Basic CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Basic Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo Success
        run: echo "Basic CI is working!"
      
      - name: List files
        run: ls -la