name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2 via SSM
      run: |
        INSTANCE_ID="i-03863f4f8f647537d"
        
        echo "🚀 Deploying to EC2 instance: $INSTANCE_ID"
        
        # Run deployment commands directly
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters commands='[
            "cd /home/ubuntu",
            "if [ -d wms ]; then cd wms && git pull origin main; else git clone https://github.com/progami/WMS_EcomOS.git wms && cd wms; fi",
            "npm ci --production",
            "npx prisma generate",
            "npm run build",
            "pm2 restart wms-app || PORT=3000 pm2 start npm --name wms-app -- start",
            "pm2 save"
          ]' \
          --output json
        
        echo "✅ Deployment command sent!"
        echo "📍 Check app at: http://3.88.163.217:3000"