name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: |
        npm run build
        
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
      run: |
        # Setup SSH key
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Create deployment package
        tar -czf deploy.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=.env* \
          .
        
        # Copy files to EC2
        scp -i private_key -o StrictHostKeyChecking=no deploy.tar.gz ${USER}@${HOST}:/tmp/
        
        # Deploy on EC2
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
          # Extract new code
          cd /var/www/wms
          tar -xzf /tmp/deploy.tar.gz
          
          # Install production dependencies
          npm install --production
          
          # Run database migrations
          npx prisma migrate deploy
          
          # Restart application
          pm2 restart wms || pm2 start npm --name wms -- start
          pm2 save
          
          # Cleanup
          rm /tmp/deploy.tar.gz
        EOF