name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Build application
      run: npm run build
      env:
        NEXT_TELEMETRY_DISABLED: 1
        
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_DNS }}
        USER: ubuntu
      run: |
        # Setup SSH key
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Create deployment package with built files
        tar -czf deploy.tar.gz \
          .next \
          public \
          prisma \
          package*.json \
          next.config.js \
          server.js \
          tsconfig.json
        
        # Copy package to EC2
        scp -i private_key -o StrictHostKeyChecking=no deploy.tar.gz ${USER}@${HOST}:/tmp/
        
        # Deploy on EC2
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
          set -e
          
          # Backup current deployment
          if [ -d /var/www/wms/.next ]; then
            tar -czf /tmp/wms-backup-$(date +%s).tar.gz -C /var/www/wms .next
          fi
          
          # Extract new code
          cd /var/www/wms
          tar -xzf /tmp/deploy.tar.gz
          
          # Install only production dependencies
          npm ci --production
          
          # Setup environment if not exists
          if [ ! -f .env.production ]; then
            cat > .env.production << EOENV
NODE_ENV=production
PORT=3000
DATABASE_URL=postgresql://wms:wms_password_2024@localhost:5432/wms
NEXTAUTH_URL=http://$(curl -s ifconfig.me)
NEXTAUTH_SECRET=$(openssl rand -base64 32)
DEMO_ADMIN_PASSWORD=Admin@2024
DEMO_STAFF_PASSWORD=Staff@2024
LOG_LEVEL=info
LOG_DIR=/var/www/wms/logs
EOENV
          fi
          
          # Run database migrations
          NODE_ENV=production npx prisma migrate deploy || echo "No pending migrations"
          
          # Restart application
          pm2 restart wms || pm2 start npm --name wms -- start
          pm2 save
          
          # Verify deployment
          sleep 5
          curl -f http://localhost:3000 || exit 1
          
          # Cleanup
          rm /tmp/deploy.tar.gz
          echo "✅ Deployment successful!"
        EOF